management:
  #server:
    #address: ${SERVER_ADDRESS:localhost}
    #port: ${SERVER_MANAGEMENT_PORT:8081}
  endpoints:
    web:
      base-path: "/actuator"
      exposure:
        include: [ "health", "info", "metrics", "prometheus" ]
  endpoint:
    health:
      show-details: when-authorized
      show-components: when-authorized