management:
  server:
    address: ${SERVER_ADDRESS:0.0.0.0}
    port: ${SERVER_MANAGEMENT_PORT:8081}
  endpoints:
    web:
      #base-path: "/actuator"
      base-path: "/management"
      exposure:
        include: [ "health", "info", "metrics", "prometheus" ]
  endpoint:
    health:
      show-details: when-authorized
      show-components: when-authorized